### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by pbaclawski** [hashicorp/packer-plugin-ansible#147]
I have found a typo that caused me some confusion. I have created a [PR for that ](https://github.com/hashicorp/packer-plugin-ansible/pull/146)but I cannot sign the CLA. Could anyone please fix it?

https://developer.hashicorp.com/packer/plugins/provisioners/ansible/ansible#troubleshooting
`set_proxy` should be changed to `use_proxy`

**Comment by nywilken** [comment]
Closed with latest pr merge. Thank you for reporting and fixing this issue.
