### ISSUE TITLE
Ansible provisioner doesn't honor winrm_use_ssl option from WinRM communicator

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/packer-plugin-ansible#159]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

When the [winrm_use_ssl](https://developer.hashicorp.com/packer/docs/communicators/winrm#winrm_use_ssl) option is specified in the template, the Ansible provisioner doesn't translate it as it should be, and uses a secure `HTTPS` connection instead of `HTTP`.

#### Reproduction Steps

1. Build a Windows image with Packer and QEMU builder, Provision it with Ansible over WinRM
2. set `winrm_use_ssl` to `False`
3. observe that the connection fails because Ansible attempts to use an HTTPS connection

### Packer version

`Packer v1.8.7`

### Simplified Packer Template

I can share the whole template with the maintainers
~~~python
source "qemu" "windows" {
  accelerator      = "kvm"
  boot_wait        = "5s"
  communicator     = "winrm"
  cpus             = "${var.cpus}"
  disk_compression = true
  disk_interface   = "ide"
  disk_size        = "${var.disk_size}"
  floppy_files     = ["${var.autounattend}", "scripts/wget-win32-static.zip", "scripts/extract_wget_zip.vbs", "scripts/setup_winrm.bat", "scripts/fixnetwork.ps1", "scripts/setup_winrm_public.bat"]
  format           = "qcow2"
  headless         = "${var.headless}"
  http_directory   = "http"
  http_port_max    = 8500
  http_port_min    = 8500
  iso_checksum     = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  memory           = "${var.memory}"
  net_device       = "rtl8139"
  shutdown_command = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  skip_compaction  = false
  vm_name          = "${var.vm_name}.qcow2"
  vnc_bind_address = "0.0.0.0"
  winrm_password   = "${var.winrm_password}"
  winrm_timeout    = "${var.winrm_timeout}"
  winrm_username   = "${var.winrm_username}"
  # do not check server certificate chain and host name
  winrm_insecure   = true
  # use HTTP
  winrm_use_ssl    = false
}

build {
  sources = ["source.qemu.windows"]

  provisioner "ansible" {
    playbook_file = "playbook.yml"
    user = "${var.winrm_username}"
    use_proxy = false
    keep_inventory_file = true
    extra_arguments = [
      "-v"
    ]
  }
}
~~~

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

```ruby
2023/05/25 13:35:32 packer-builder-qemu plugin: [ERROR] connection error: unknown error Post "http://127.0.0.1:3030/wsman": read tcp 127.0.0.1:40956->127.0.0.1:3030: read: connection reset by peer
2023/05/25 13:35:32 packer-builder-qemu plugin: [ERROR] WinRM connection err: unknown error Post "http://127.0.0.1:3030/wsman": read tcp 127.0.0.1:40956->127.0.0.1:3030: read: connection reset by peer
2023/05/25 13:35:37 packer-builder-qemu plugin: [INFO] Attempting WinRM connection...
2023/05/25 13:35:37 packer-builder-qemu plugin: [DEBUG] connecting to remote shell using WinRM
2023/05/25 13:36:31 packer-builder-qemu plugin: [ERROR] connection error: http response error: 401 - invalid content type
2023/05/25 13:36:31 packer-builder-qemu plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type
2023/05/25 13:36:36 packer-builder-qemu plugin: [INFO] Attempting WinRM connection...
2023/05/25 13:36:36 packer-builder-qemu plugin: [DEBUG] connecting to remote shell using WinRM
2023/05/25 13:36:36 packer-builder-qemu plugin: [ERROR] connection error: http response error: 401 - invalid content type
2023/05/25 13:36:36 packer-builder-qemu plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type
2023/05/25 13:36:41 packer-builder-qemu plugin: [INFO] Attempting WinRM connection...
2023/05/25 13:36:41 packer-builder-qemu plugin: [DEBUG] connecting to remote shell using WinRM
2023/05/25 13:36:46 packer-builder-qemu plugin: Checking that WinRM is connected with: 'powershell.exe -EncodedCommand JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwA7AGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAB2AGEAcgBpAGEAYgBsAGUAOgBnAGwAbwBiAGEAbAA6AFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlACkAewAkAFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlAD0AJwBTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlACcAfQA7ACAAZQBjAGgAbwAgACIAVwBpAG4AUgBNACAAYwBvAG4AbgBlAGMAdABlAGQALgAiAA=='
2023/05/25 13:36:46 packer-builder-qemu plugin: [INFO] starting remote command: powershell.exe -EncodedCommand JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwA7AGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAB2AGEAcgBpAGEAYgBsAGUAOgBnAGwAbwBiAGEAbAA6AFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlACkAewAkAFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlAD0AJwBTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlACcAfQA7ACAAZQBjAGgAbwAgACIAVwBpAG4AUgBNACAAYwBvAG4AbgBlAGMAdABlAGQALgAiAA==
2023/05/25 13:36:47 packer-builder-qemu plugin: [INFO] command 'powershell.exe -EncodedCommand JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwA7AGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAB2AGEAcgBpAGEAYgBsAGUAOgBnAGwAbwBiAGEAbAA6AFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlACkAewAkAFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlAD0AJwBTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlACcAfQA7ACAAZQBjAGgAbwAgACIAVwBpAG4AUgBNACAAYwBvAG4AbgBlAGMAdABlAGQALgAiAA==' exited with code: 0
    qemu.windows: WinRM connected.
2023/05/25 13:36:47 packer-builder-qemu plugin: Connected to machine
==> qemu.windows: Connected to WinRM!
2023/05/25 13:36:47 packer-builder-qemu plugin: Running the provision hook
2023/05/25 13:36:47 [INFO] (telemetry) Starting provisioner ansible
2023/05/25 13:36:48 packer-provisioner-ansible plugin: ansible-playbook version: 2.14.5
==> qemu.windows: Provisioning with Ansible...
    qemu.windows: 	Using WinRM Password from Packer communicator...
    qemu.windows: Not using Proxy adapter for Ansible run:
    qemu.windows: 	Using WinRM Password from Packer communicator...
2023/05/25 13:36:48 packer-provisioner-ansible plugin: Creating inventory file for Ansible run...
==> qemu.windows: Executing Ansible: ansible-playbook -e packer_build_name="windows" -e packer_builder_type=qemu -e packer_http_addr=10.0.2.2:8500 -v -e ansible_password=***** -i /tmp/packer-provisioner-ansible3851180393 /home/wenzel/Projets/kafl.targets/windows_x86_64-userspace/template/playbook.yml
    qemu.windows: Using /home/wenzel/Projets/kafl.targets/windows_x86_64-userspace/template/ansible.cfg as config file
    qemu.windows:
    qemu.windows: PLAY [Deploy] ******************************************************************
    qemu.windows:
    qemu.windows: TASK [Gathering Facts] *********************************************************
    qemu.windows: fatal: [default]: UNREACHABLE! => {
    qemu.windows:     "changed": false,
    qemu.windows:     "unreachable": true
    qemu.windows: }
    qemu.windows:
    qemu.windows: MSG:
    qemu.windows:
    qemu.windows: basic: HTTPSConnectionPool(host='127.0.0.1', port=3030): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)')))
    qemu.windows:
    qemu.windows: PLAY RECAP *********************************************************************
    qemu.windows: default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
    qemu.windows:
2023/05/25 13:36:49 [INFO] (telemetry) ending ansible
==> qemu.windows: Error executing Ansible: Non-zero exit status: exit status 4
==> qemu.windows: Step "StepProvision" failed
==> qemu.windows: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? 
```

Content of `/tmp/packer-provisioner-ansible3851180393`inventory:

```INI
default ansible_host=127.0.0.1 ansible_connection=winrm ansible_winrm_transport=basic ansible_shell_type=powershell ansible_user=vagrant ansible_port=3030
```

### Idea :bulb: 

According to [Ansible Windows Remote Management Docs](https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html)

_"ansible_winrm_scheme: Specify the connection scheme (http or https) to use for the WinRM connection. Ansible uses https by default unless ansible_port is 5985"_

So Ansible keeps HTTPS scheme because Packer configures a special port forwarding which is not `5985`.

### Temporary Workaround

Just add `-e ansible_winrm_scheme` to the extra args
![image](https://github.com/hashicorp/packer/assets/964610/6323ab65-3283-4e43-a921-e392c917d54e)

Thanks !

**Comment by lbajolet-hashicorp** [comment]
Hi @Wenzel,

In this case this is not directly a Packer issue, but something for the Ansible plugin, so I will transfer the issue over there for tracking.

On another note, if the workaround involves a change to the command-line, this looks like something the plugin can do, if it has access to this information (that may be the case, but we'll have to double-check that).
I'll take a look at this today, I'll let you know.

Thanks for providing the configuration for testing, I'll try to use it to replicate and fix this.

**Comment by lbajolet-hashicorp** [comment]
Hi again @Wenzel,

Trying to locally test the template, I'm unfortunately unable to configure WinRM to work over plain HTTP, Windows is not my strong suit to be honest. If possible, could you share your autounattend, and the scripts you're referencing in the floppy files? That'd probably help me get a working test environment for this issue.

Aside from that, unfortunately, the provider does not inherit the communicator's configuration information, so we won't be able to automatically infer that HTTP is to be used by Ansible to connect.
In this case, there's the workaround you proposed, and we can maybe add a simple flag (something like `winrm_use_http`), with some extra documentation, to force Ansible to define the WinRM scheme to HTTP. This would in effect amount to adding the extra argument to ansible's command line, with a clearer name.
It's not perfect, but it would make it easier on our users that want to provision Windows images over WinRM/HTTP by documenting the required steps in such cases.
Would that be acceptable in your opinion?

**Comment by Wenzel** [comment]
Hi @lbajolet-hashicorp 

> Trying to locally test the template, I'm unfortunately unable to configure WinRM to work over plain HTTP, Windows is not my strong suit to be honest. If possible, could you share your autounattend, and the scripts you're referencing in the floppy files? That'd probably help me get a working test environment for this issue.

Sure, totally understand
You can find the template i'm currently using in this directory:
https://github.com/Wenzel/kafl.targets/tree/fix_windows_userspace/windows_x86_64-userspace/template

`PACKER_LOG=1 packer build -var-file win8.pkrvars.hcl -only qemu.windows -on-error=ask .` and you should be good to go :rocket: 

Remove this line to repro the bug:
https://github.com/Wenzel/kafl.targets/blob/fix_windows_userspace/windows_x86_64-userspace/template/windows.json.pkr.hcl#L126

**Comment by Wenzel** [comment]
> Aside from that, unfortunately, the provider does not inherit the communicator's configuration information, so we won't be able to automatically infer that HTTP is to be used by Ansible to connect.
In this case, there's the workaround you proposed, and we can maybe add a simple flag (something like winrm_use_http), with some extra documentation, to force Ansible to define the WinRM scheme to HTTP. This would in effect amount to adding the extra argument to ansible's command line, with a clearer name.
It's not perfect, but it would make it easier on our users that want to provision Windows images over WinRM/HTTP by documenting the required steps in such cases.
Would that be acceptable in your opinion?

I guess adding an extra option in the config isn't a big deal.
But I would rather name it `winrm_use_ssl` also, which defaults to `True` so that it clearly refers to the same option used by the WinRM communicator ?
