### ISSUE TITLE
{{ .WinRMPassword }} is not interpolated

### ISSUE THREAD

**Issue by flixman** [hashicorp/packer-plugin-ansible#56]
I have migrated my packer files from json to hcl2. The ansible provisioner does not recognize anymore the "{{ .WinRMPassword }}" template to add the ansible_password as extra-arguments. I have checked the source code of the plugin and I have found out that in case ansible_password is not found in extra-arguments, connection is winrm and 'use proxy' is false, the password gets added by default to the command line and everything works, but maybe this should be added somewhere to the documentation?

**Comment by SwampDragons** [comment]
HCL uses a different structure for build variables: https://www.packer.io/docs/templates/hcl_templates/contextual-variables#build-variables

Try using `${build.Password}` instead of `{{.WinRMPassword}}`

**Comment by flixman** [comment]
hey @SwampDragons, thank you for your answer. I will give it a try, and indeed seems it will work, but this documentation then conflicts with that of the ansible provisioner, https://www.packer.io/docs/provisioners/ansible/ansible, where it says
"_[...] For example, if you are running a Windows build on AWS, Azure, Google Compute, or OpenStack and would like to access the auto-generated password that Packer uses to connect to a Windows instance via WinRM, you can use the template variable {{.WinRMPassword}} in this option. [...]_".
In any case, knowing that you guys are aware of this, I guess I can close this issue? :-)

**Comment by SwampDragons** [comment]
I'll update the docs
