### ISSUE TITLE
Use different signature algorithm for SSH host key

### ISSUE THREAD

**Issue by heroin-moose** [hashicorp/packer-plugin-ansible#69]
Currently this plugin generates RSA keys:

https://github.com/hashicorp/packer-plugin-ansible/blob/97b6b771eef32c620d0ea16669a0d36aed79d025/provisioner/ansible/provisioner.go#L993

However, RSA/SHA-1 was deprecated in the latest OpenSSH release ([changelog](https://www.openssh.com/txt/release-8.8)) and my builds fail with the following error:

```
qemu.example-vm: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 37115: no matching host key type
found. Their offer: ssh-rsa", "unreachable": true}
```

Please, consider changing the algorithm to something newer.

**Comment by klausenbusk** [comment]
I did some research and switching to something else (ex:Ed25519) is more difficult than anticipated, as Go doesn't support the relevant key format (https://github.com/golang/go/issues/37132).

See also this issue: https://github.com/golang/go/issues/37278 for RFC8332 support.

Related issue: https://github.com/hashicorp/packer/issues/8609

**Comment by yasn77** [comment]
Issue is also reported here #53 

I am facing a similar problem with Arch Linux, I am getting around it right now by using docker to run packer, but it's pretty annoying :)

**Comment by klausenbusk** [comment]
x/crypto supports RSA SHA-2 (https://github.com/golang/crypto/commit/b4de73f9ece8163b492578e101e4ef8923ac2c5c) now. So updating `golang.org/x/crypto` should fix this issue.

**Comment by NHAS** [comment]
I am also effected by this issue. Has there been any movement on this?

**Comment by NHAS** [comment]
Another way you can get around this, which I think is rather clean is re-enabling the weak rsa-sha1 agorithm within your ssh client.

@ispirals 

E.g Add this to your packer json/hcl

```json
 "ansible_ssh_extra_args": [
                "-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa"
]
```

**Comment by adds68** [comment]
> Issue is also reported here #53
> 
> I am facing a similar problem with Arch Linux, I am getting around it right now by using docker to run packer, but it's pretty annoying :)

Hey, interested to know how this workaround is used, do you have any examples?

**Comment by stefangweichinger** [comment]
same here: could use a working example, fails here with virtualbox-iso

```
==> debian.virtualbox-iso.bullseye: Executing Ansible: ansible-playbook -e packer_build_name="base-debian-amd64" -e packer_builder_type=virtualbox-iso -e packer_http_addr=10.0.2.2:8873 --ssh-extra-args '-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa' -e ansible_ssh_private_key_file=/tmp/ansible-key43104058 -i /tmp/packer-provisioner-ansible2143489858 /home/sgw/projects/packer/my-work/packer_sgw_builds/ansible/*****-debian-11-guest-additions.yml
    debian.virtualbox-iso.bullseye:
    debian.virtualbox-iso.bullseye: PLAY [all] *********************************************************************
    debian.virtualbox-iso.bullseye:
    debian.virtualbox-iso.bullseye: TASK [Gathering Facts] *********************************************************
    debian.virtualbox-iso.bullseye: fatal: [default]: FAILED! => {"msg": "failed to transfer file to /home/sgw/.ansible/tmp/ansible-local-124735o9cwss1j/tmpe8pwoul3 /home/vagrant/.ansible/tmp/ansible-tmp-1651577057.3591588-124739-192345091164490/AnsiballZ_setup.py:\n\n"}
    debian.virtualbox-iso.bullseye:
    debian.virtualbox-iso.bullseye: PLAY RECAP *********************************************************************
    debian.virtualbox-iso.bullseye: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    debian.virtualbox-iso.bullseye:
==> debian.virtualbox-iso.bullseye: Provisioning step had errors: Running the cleanup provisioner, if present...
==> debian.virtualbox-iso.bullseye: Cleaning up floppy disk...
==> debian.virtualbox-iso.bullseye: Deregistering and deleting VM...
==> debian.virtualbox-iso.bullseye: Deleting output directory...
Build 'debian.virtualbox-iso.bullseye' errored after 6 minutes 40 seconds: Error executing Ansible: Non-zero exit status: exit status 2
```

I have this in my "debian-improved.pkr.hcl":

```
provisioner "ansible" {                                                       
  playbook_file = "ansible/vagrant-debian-11-guest-additions.yml"             
  user          = "${var.ssh_username}"                                       
  ansible_ssh_extra_args = [                                                    
                "-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa"
 ]                                                                               
   }        

This is Packer 1.8.0

**Comment by adrianlzt** [comment]
I'm using this configuration in the ``.ssh/config`` file to avoid the error (no need for the ``ansible_ssh_extra_args`` config):

```
Host 127.0.0.1
      HostKeyAlgorithms +ssh-rsa
      PubkeyAcceptedKeyTypes +ssh-rsa
```

**Comment by lsampaioweb** [comment]
So the only option to make it work is by using the workaround??? I am having the same problem. I didn't like this option...

**Comment by Syntax3rror404** [comment]
`"ansible_ssh_extra_args": ["-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa"]`
helped my out with rocky 9

**Comment by danwashusen** [comment]
Setting `use_proxy = false` fixed it for me...

https://www.packer.io/plugins/provisioners/ansible/ansible#use_proxy

**Comment by Fjan** [comment]
For anyone else running into the error pointed out by @stefangweichinger, the solution for that is in https://github.com/hashicorp/packer/issues/11783 so the total snippet that works becomes:
```
            "ansible_ssh_extra_args": ["-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa -o IdentitiesOnly=yes"],
            "extra_arguments": [ "--scp-extra-args", "'-O'" ],
```

**Comment by lethargosapatheia** [comment]
The problem with this solution (+ssh-rsa) is that it ignores the fact that some people actually use the much more secure ed25519 (which should already be standard by now). And that doesn't work in my case in Ubuntu 22.04, but it has been working on Ubuntu 20.04 for some reason. So that's great.

**Comment by jdptechnc** [comment]
Any plans to fix (with a real fix, and not using rsa) this issue?  For ansible control environments on systems using a modern crypto policy (no sha1), just adding +rsa to the ansible config will not work.

**Comment by lbajolet-hashicorp** [comment]
Update: PR is open, I didn't go for `ed25519` in the end since the serialised key is only accepted by `OpenSSH` when in its native format, which the Go libraries don't support yet.

I'll probably iterate on the PR before we can merge it, as much as ECDSA should be well-supported, I would like to introduce an option to fallback on RSA-SHA1 for users that desire to do so (if they run Packer/Ansible on an old distribution with OpenSSH that doesn't support ECDSA at all). I'll amend this PR, but in the meantime, I encourage you all to test out this change by either locally compiling the plugin and testing it on your configurations.

Hope that fixes this problem! Sorry for letting that linger for this long.

**Comment by Kaappihullu** [comment]
> > ```json
> > "ansible_ssh_extra_args": [
> >                 "-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa"
> > ]
> > ```
> 
> after adding the above snippet I am getting the following error. Any help on this
> 
> ```
> {
>     amazon-ebs.ubuntu18:     "changed": false,
>     amazon-ebs.ubuntu18:     "msg": "Failed to connect to the host via ssh: command-line line 0: keyword hostkeyalgorithms extra arguments at end of line",
>     amazon-ebs.ubuntu18:     "unreachable": true
>     amazon-ebs.ubuntu18: }
> ```

for some reason apparently by no seen reason (none that I could find, one minute it works and then I get this same error) ansible sometimes wraps ansible_ssh_extra_args with '', so the ssh command fails. But if you use extra_arguments": [  "--ssh-extra-args", "-o IdentitiesOnly=yes -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa" ] instead, it will work.

**Comment by eschulma** [comment]
The latest version of the ansible plugin fixes this. Add

`packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
  }
}`

to your config file and run `packer init`

**Comment by msandu62** [comment]
Facing the same issue  "msg": "Failed to connect to the host via ssh: command-line line 0: keyword hostkeyalgorithms extra arguments at end of line" - any solution?

**Comment by lbajolet-hashicorp** [comment]
Hi @msandu62,

Regarding the SSH problem, as mentioned above, this problem has been fixed with version 1.1.0 of the plugin, please consider updating to this version or above if you are experiencing the RSA-key issue.

If you do need to specify extra SSH arguments even on the latest version of the plugin, the "extra arguments at end of line" is described by issue #158, a PR is in the pipeline for this, which I'll review today.

**Comment by dnv** [comment]
Not really sure how to proceed... I have an RHEL 8 JSON template I've previously succesfully used against 8.3, 8.5 and 8.8, now trying to build against 8.9, I am running head first into this very issue. My template is JSON and while my 9 template is HCL, I'd really rather not have to spend the time converting the old 8 JSON template to HCL and tidying it all up just so that I could use "packer init" to enforce requiring a newer Ansible plugin version.

I tried the 'use_proxy = false' workaround suggested here, but somehow, in that mode, packer seemingly isn't even trying to use password authentication and fails all authentication methods.

**Comment by lbajolet-hashicorp** [comment]
Hi @dnv,

Without updating to HCL2 for `required_plugins`, you can always install more recent versions of the plugin through `packer plugins install`, in your case if you want to require v1.1.0 (latest), you can run this:

```sh
$ packer plugins install "github.com/hashicorp/ansible" "v1.1.0"
```

Assuming it's not already installed, this will get v1.1.0 of the plugin, and unless some other version takes precedence over it, Packer will start using it for all your builds that use Ansible.

If you want to make sure you're using it, I encourage you to run packer with the `PACKER_LOG=1` environment variable set so you get more verbose logs, which will tell you which plugins are being used/loaded for running your builds.

**Comment by dnv** [comment]
@lbajolet-hashicorp thank you so much!

This almost got me there, after manually updating the Ansible plugin, I faced another error complaining about a missing /usr/lib/sftp-server, but this was in turn solved by adding the following to ansible provisioner configuration:

_"extra_arguments": [ "--scp-extra-args", "'-O'" ]_
